# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47970575babba49f96f647606b0c9f776eab456043d21948f9fdefbfcf18aeda0ca5b51887901046eea508d30368fe4f17bb8af40425f85ea84ced807376a87

test:
  secret_key_base: e1e37ddd1cc97198147565b145ccecf65b571b62134246551570b97f203544b07a520709c5df9d62c18c7ad30a069be8b2ea54fe4a264596ab553f4e90873396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
